### PR TITLE
Apply armor animations to character for Early Construction Light/Heavy Armors

### PR DESCRIPTION
**Pull request by millerlarson**
I noticed that in game, the light and heavy early construction armors showed the character as having no armor applied.

Poked around until I found where it seemed another mod was able to make this work.  Adapted a few lines and did a quick test, seems to work.

Also fixed some links with README.md and what I think was some other small typos in data.lua.

### CODE REVIEW

**Comment by Aidiakapi** [comment]
I just checked the code, and it looks fantastic. I'll have to test it in-game tomorrow, and I'll ship a release with it too. Your effort is much appreciated!

**Comment by millerlarson** [comment]
It could probably use some clean up.  I'm not 100% clear on exactly what it's doing; it looked like it was doing what I was wanting and so I swapped a few of the pertinent bits and it seemed to work.

If I have time, I'll see if I can simplify it a bit and do some more testing.  Figure an "if or" would do just as well as an "if elseif," especially when the outcome would be the same.

Again, [thank you](https://mods.factorio.com/mod/early_construction/discussion/5fe29894961804b10af01a56) for this mod!

**Comment by millerlarson** [comment]
Eh, anything else I tried just seemed to break it.  I suppose I'll just leave it as is and let you know if I run into any issues.

**Comment by Aidiakapi** [comment]
I've uploaded the new version to the mod portal @ 0.9.1, thanks again for the contribution!

**Pull request merged**
